README.md, pom.xml, src/main/java/dasniko/testcontainers/keycloak/KeycloakContainer.java
=> Update Keycloak version to 11.0.2

README.md, pom.xml, src/main/java/dasniko/testcontainers/keycloak/KeycloakContainer.java
=> GH-12 Update Keycloak version to 12.0.4

README.md, pom.xml, src/main/java/dasniko/testcontainers/keycloak/KeycloakContainer.java
=> GH-30 Update Keycloak version to 13.0.1

src/main/java/dasniko/testcontainers/keycloak/KeycloakContainer.java
Makes it work for me locally.
Test Case: I downloaded dasniko/keycloak-extensions-demo from Github and run dasniko.keycloak.user.PeanutsUserProviderTest using IntelliJ under Windows 10 / Docker Desktop.
Same thing occured in a different Project, which is why i tried to reproduce it in a known well working state. By merely changing in testcontainers-keycloak.version to the values provided below, reproduction works.
Sorry for the odd formatting, but i think it's good enough.
Sincerly
Björn
<details> 
<summary>Using locally build 1.9.1-SNAPSHOT</summary>
<code>
0    [main] INFO  org.testcontainers.utility.ImageNameSubstitutor  - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor') …
=> Replace MountableFile.forClasspath with MountableFile.forHostPath

src/main/java/dasniko/testcontainers/keycloak/KeycloakContainer.java
This address the first issue of #64
=> use current thread context loader for load resources

src/main/java/dasniko/testcontainers/keycloak/KeycloakContainer.java
relates to  https://github.com/dasniko/testcontainers-keycloak/issues/64#issuecomment-1077969489
=> close keycloak admin client

pom.xml, src/main/java/dasniko/testcontainers/keycloak/KeycloakContainer.java, src/test/java/dasniko/testcontainers/keycloak/KeycloakContainerTest.java, src/test/resources/second-test-folder/first-test-folder/test-realm.json, src/test/resources/single-test-folder/test-realm.json
=> Allow import realm files from directories

src/main/java/dasniko/testcontainers/keycloak/KeycloakContainer.java, src/test/java/dasniko/testcontainers/keycloak/KeycloakContainerHttpsTest.java
=> Fix Admin client cannot connect when TLS is enabled

src/main/java/dasniko/testcontainers/keycloak/KeycloakContainer.java, src/test/java/dasniko/testcontainers/keycloak/KeycloakContainerTest.java
… and add possibility to disable it with method #withDisabledCaching()
As discussed in https://github.com/dasniko/testcontainers-keycloak/issues/85.
@dasniko: Implementation is based on your latest comment in that issue: https://github.com/dasniko/testcontainers-keycloak/issues/85#issuecomment-1236396805
=> enable Keycloak caching per default

src/main/java/dasniko/testcontainers/keycloak/ExtendableKeycloakContainer.java, src/test/java/dasniko/testcontainers/keycloak/KeycloakContainerTest.java
This PR allows to activate the metrics endpoint.
see https://www.keycloak.org/server/configuration-metrics
=> Support metrics

pom.xml, src/main/java/dasniko/testcontainers/keycloak/ExtendableKeycloakContainer.java, src/test/java/dasniko/testcontainers/keycloak/KeycloakContainerTest.java
Resolves dasniko/testcontainers-keycloak#117
=> Add option to remotely debug Keycloak

src/main/java/dasniko/testcontainers/keycloak/ExtendableKeycloakContainer.java
=> copy realm file with permissions

src/main/java/dasniko/testcontainers/keycloak/ExtendableKeycloakContainer.java
=> allow for multiple locations

README.md, src/main/java/dasniko/testcontainers/keycloak/ExtendableKeycloakContainer.java
=> Upgrade to Keycloak 25

src/main/java/dasniko/testcontainers/keycloak/ExtendableKeycloakContainer.java
=> use the new bootstrap admin env vars

src/main/java/dasniko/testcontainers/keycloak/ExtendableKeycloakContainer.java, src/test/java/dasniko/testcontainers/keycloak/KeycloakContainerExtensionReuseTest.java, src/test/java/dasniko/testcontainers/keycloak/KeycloakContainerExtensionTest.java
=> add distinct method to disable lightweight access token for admin-cli

README.md, src/main/java/dasniko/testcontainers/keycloak/ExtendableKeycloakContainer.java, src/test/java/dasniko/testcontainers/keycloak/KeycloakContainerTest.java
Hey @dasniko ,
I added a convinience method for getting the management URL.
Please let me know what you think.
=> Added distinct method for getting Management URL from Testcontainer

README.md, src/main/java/dasniko/testcontainers/keycloak/ExtendableKeycloakContainer.java, src/test/java/dasniko/testcontainers/keycloak/KeycloakContainerOptimizedTest.java, src/test/java/dasniko/testcontainers/keycloak/KeycloakContainerTest.java, src/test/resources/Dockerfile
Could close: https://github.com/dasniko/testcontainers-keycloak/issues/166
Things that at least need to be done before merge:
- more tests(See testfile)
- documentation
=> Add capability to use --optimized option

pom.xml, src/main/java/dasniko/testcontainers/keycloak/ExtendableKeycloakContainer.java, src/test/java/dasniko/testcontainers/keycloak/KeycloakContainerTest.java
=> rollback to jdk-11 compatibility

src/main/java/dasniko/testcontainers/keycloak/ExtendableKeycloakContainer.java
=> remove deprecation flag, as this is also undeprecated in Keycloak itself
